version: 2

builds:
  - main: ./cmd/thermal
    binary: thermal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/jadmadi/thermal/internal/version.Version={{ .Version }}
      - -X github.com/jadmadi/thermal/internal/version.Commit={{ .ShortCommit }}
      - -X github.com/jadmadi/thermal/internal/version.Date={{ .Date }}

upx:
  - enabled: true
    compress: "9"
    goos:
      - linux
      - windows

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
