#!/bin/bash
# Generated by 'sila install' for Cognition Devin
set -e
echo "· [sila] verifying environment in Devin sandbox..."
if command -v sila >/dev/null 2>&1; then
    sila doctor || true
    sila prime || true
fi
